// Copyright 2011 Google Inc. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
package com.google.android.apps.body;

import java.util.HashMap;
import java.util.Map;

/**
 * Maps resource names to pack file names. Mostly autogenerated.
 */
public class FP {
    public static class FPEntry {
        int file;
        int start;
        int length;
        FPEntry(int file, int start, int length) {
            this.file = file;
            this.start = start;
            this.length = length;
        }
    }
    public static FPEntry get(String key) {
        return fpEntries.get(key);
    }
    @SuppressWarnings("serial")
    private static final Map<String, FPEntry> fpEntries = new HashMap<String, FPEntry>();
    static {
         // FIXME(thakis): Make this more configurable.
     	FPEntry entry = new FPEntry(R.raw.f_3b3ec079, 0, 10080);
 		fpEntries.put("bin/f_skin/Eye_SG1_indices.utf8", entry);
 		entry = new FPEntry(R.raw.f_3b3ec079, 10080, 147120);
 		fpEntries.put("bin/f_skin/Female_Repro_SG4_indices.utf8", entry);
 		entry = new FPEntry(R.raw.f_3b3ec079, 157200, 7056);
 		fpEntries.put("bin/f_skin/Outer_Eye_SG1_indices.utf8", entry);
 		entry = new FPEntry(R.raw.f_3b3ec079, 164256, 10248);
 		fpEntries.put("bin/f_skin/clothes1_indices.utf8", entry);
 		entry = new FPEntry(R.raw.f_3b3ec079, 174504, 31890);
 		fpEntries.put("bin/f_skin/f_skin_Body_SG1_indices.utf8", entry);
 		entry = new FPEntry(R.raw.f_3b3ec079, 206394, 14352);
 		fpEntries.put("bin/f_skin/f_skin_Head_SG1_indices.utf8", entry);
 		entry = new FPEntry(R.raw.f_3b3ec079, 220746, 8904);
 		fpEntries.put("bin/f_skin/hair_base_SG1_indices.utf8", entry);
 		entry = new FPEntry(R.raw.f_3b3ec079, 229650, 17304);
 		fpEntries.put("bin/f_skin/hair_strandsSG1_indices.utf8", entry);
 		entry = new FPEntry(R.raw.f_3b3ec079, 246954, 1890);
 		fpEntries.put("bin/f_skin/pupil1_indices.utf8", entry);
 		
 		entry = new FPEntry(R.raw.f_d717e27c, 0, 14624);
 		fpEntries.put("bin/f_skin/Eye_SG1_attribs.utf8", entry);
 		entry = new FPEntry(R.raw.f_d717e27c, 14624, 212112);
 		fpEntries.put("bin/f_skin/Female_Repro_SG4_attribs.utf8", entry);
 		entry = new FPEntry(R.raw.f_d717e27c, 226736, 9616);
 		fpEntries.put("bin/f_skin/Outer_Eye_SG1_attribs.utf8", entry);
 		entry = new FPEntry(R.raw.f_d717e27c, 236352, 14760);
 		fpEntries.put("bin/f_skin/clothes1_attribs.utf8", entry);
 		entry = new FPEntry(R.raw.f_d717e27c, 251112, 68984);
 		fpEntries.put("bin/f_skin/f_skin_Body_SG1_attribs.utf8", entry);
 		entry = new FPEntry(R.raw.f_d717e27c, 320096, 72072);
 		fpEntries.put("bin/f_skin/f_skin_Head_SG1_attribs.utf8", entry);
 		entry = new FPEntry(R.raw.f_d717e27c, 392168, 13072);
 		fpEntries.put("bin/f_skin/hair_base_SG1_attribs.utf8", entry);
 		entry = new FPEntry(R.raw.f_d717e27c, 405240, 31824);
 		fpEntries.put("bin/f_skin/hair_strandsSG1_attribs.utf8", entry);
 		entry = new FPEntry(R.raw.f_d717e27c, 437064, 6512);
 		fpEntries.put("bin/f_skin/pupil1_attribs.utf8", entry);
 		
 		entry = new FPEntry(R.raw.f_d7404dbc, 0, 61686);
 		fpEntries.put("bin/f_muscles/ArmE1_indices.utf8", entry);
 		entry = new FPEntry(R.raw.f_d7404dbc, 61686, 36510);
 		fpEntries.put("bin/f_muscles/Torso_SideB_SG3_indices.utf8", entry);
 		entry = new FPEntry(R.raw.f_d7404dbc, 98196, 32550);
 		fpEntries.put("bin/f_muscles/headA_SG2_indices.utf8", entry);
 		entry = new FPEntry(R.raw.f_d7404dbc, 130746, 16302);
 		fpEntries.put("bin/f_muscles/hip_SG1_indices.utf8", entry);
 		entry = new FPEntry(R.raw.f_d7404dbc, 147048, 70764);
 		fpEntries.put("bin/f_muscles/lambert2SG1_indices.utf8", entry);
 		entry = new FPEntry(R.raw.f_d7404dbc, 217812, 5316);
 		fpEntries.put("bin/f_muscles/lambert6SG1_indices.utf8", entry);
 		entry = new FPEntry(R.raw.f_d7404dbc, 223128, 75120);
 		fpEntries.put("bin/f_muscles/neckB_SG1_indices.utf8", entry);
 		entry = new FPEntry(R.raw.f_d7404dbc, 298248, 57804);
 		fpEntries.put("bin/f_muscles/torso_sideA_SG1_indices.utf8", entry);
 		entry = new FPEntry(R.raw.f_d7404dbc, 356052, 28980);
 		fpEntries.put("bin/f_muscles/vr_muscle_work_1_armA_SG1_indices.utf8", entry);
 		entry = new FPEntry(R.raw.f_d7404dbc, 385032, 7158);
 		fpEntries.put("bin/f_muscles/vr_muscle_work_1_headB_mat1_indices.utf8", entry);
 		entry = new FPEntry(R.raw.f_315c72b9, 0, 98576);
 		fpEntries.put("bin/f_muscles/ArmE1_attribs.utf8", entry);
 		entry = new FPEntry(R.raw.f_315c72b9, 98576, 64232);
 		fpEntries.put("bin/f_muscles/Torso_SideB_SG3_attribs.utf8", entry);
 		entry = new FPEntry(R.raw.f_315c72b9, 162808, 51696);
 		fpEntries.put("bin/f_muscles/headA_SG2_attribs.utf8", entry);
 		entry = new FPEntry(R.raw.f_315c72b9, 214504, 27008);
 		fpEntries.put("bin/f_muscles/hip_SG1_attribs.utf8", entry);
 		entry = new FPEntry(R.raw.f_315c72b9, 241512, 111856);
 		fpEntries.put("bin/f_muscles/lambert2SG1_attribs.utf8", entry);
 		entry = new FPEntry(R.raw.f_315c72b9, 353368, 7536);
 		fpEntries.put("bin/f_muscles/lambert6SG1_attribs.utf8", entry);
 		entry = new FPEntry(R.raw.f_315c72b9, 360904, 125584);
 		fpEntries.put("bin/f_muscles/neckB_SG1_attribs.utf8", entry);
 		entry = new FPEntry(R.raw.f_315c72b9, 486488, 83304);
 		fpEntries.put("bin/f_muscles/torso_sideA_SG1_attribs.utf8", entry);
 		entry = new FPEntry(R.raw.f_315c72b9, 569792, 52240);
 		fpEntries.put("bin/f_muscles/vr_muscle_work_1_armA_SG1_attribs.utf8", entry);
 		entry = new FPEntry(R.raw.f_315c72b9, 622032, 11280);
 		fpEntries.put("bin/f_muscles/vr_muscle_work_1_headB_mat1_attribs.utf8", entry);
 		entry = new FPEntry(R.raw.f_d7404dbc, 0, 61686);
 		fpEntries.put("bin/f_muscles/ArmE1_indices.utf8", entry);
 		entry = new FPEntry(R.raw.f_d7404dbc, 61686, 36510);
 		fpEntries.put("bin/f_muscles/Torso_SideB_SG3_indices.utf8", entry);
 		entry = new FPEntry(R.raw.f_d7404dbc, 98196, 32550);
 		fpEntries.put("bin/f_muscles/headA_SG2_indices.utf8", entry);
 		entry = new FPEntry(R.raw.f_d7404dbc, 130746, 16302);
 		fpEntries.put("bin/f_muscles/hip_SG1_indices.utf8", entry);
 		entry = new FPEntry(R.raw.f_d7404dbc, 147048, 70764);
 		fpEntries.put("bin/f_muscles/lambert2SG1_indices.utf8", entry);
 		entry = new FPEntry(R.raw.f_d7404dbc, 217812, 5316);
 		fpEntries.put("bin/f_muscles/lambert6SG1_indices.utf8", entry);
 		entry = new FPEntry(R.raw.f_d7404dbc, 223128, 75120);
 		fpEntries.put("bin/f_muscles/neckB_SG1_indices.utf8", entry);
 		entry = new FPEntry(R.raw.f_d7404dbc, 298248, 57804);
 		fpEntries.put("bin/f_muscles/torso_sideA_SG1_indices.utf8", entry);
 		entry = new FPEntry(R.raw.f_d7404dbc, 356052, 28980);
 		fpEntries.put("bin/f_muscles/vr_muscle_work_1_armA_SG1_indices.utf8", entry);
 		entry = new FPEntry(R.raw.f_d7404dbc, 385032, 7158);
 		fpEntries.put("bin/f_muscles/vr_muscle_work_1_headB_mat1_indices.utf8", entry);
 		
 		entry = new FPEntry(R.raw.f_315c72b9, 0, 98576);
 		fpEntries.put("bin/f_muscles/ArmE1_attribs.utf8", entry);
 		entry = new FPEntry(R.raw.f_315c72b9, 98576, 64232);
 		fpEntries.put("bin/f_muscles/Torso_SideB_SG3_attribs.utf8", entry);
 		entry = new FPEntry(R.raw.f_315c72b9, 162808, 51696);
 		fpEntries.put("bin/f_muscles/headA_SG2_attribs.utf8", entry);
 		entry = new FPEntry(R.raw.f_315c72b9, 214504, 27008);
 		fpEntries.put("bin/f_muscles/hip_SG1_attribs.utf8", entry);
 		entry = new FPEntry(R.raw.f_315c72b9, 241512, 111856);
 		fpEntries.put("bin/f_muscles/lambert2SG1_attribs.utf8", entry);
 		entry = new FPEntry(R.raw.f_315c72b9, 353368, 7536);
 		fpEntries.put("bin/f_muscles/lambert6SG1_attribs.utf8", entry);
 		entry = new FPEntry(R.raw.f_315c72b9, 360904, 125584);
 		fpEntries.put("bin/f_muscles/neckB_SG1_attribs.utf8", entry);
 		entry = new FPEntry(R.raw.f_315c72b9, 486488, 83304);
 		fpEntries.put("bin/f_muscles/torso_sideA_SG1_attribs.utf8", entry);
 		entry = new FPEntry(R.raw.f_315c72b9, 569792, 52240);
 		fpEntries.put("bin/f_muscles/vr_muscle_work_1_armA_SG1_attribs.utf8", entry);
 		entry = new FPEntry(R.raw.f_315c72b9, 622032, 11280);
 		fpEntries.put("bin/f_muscles/vr_muscle_work_1_headB_mat1_attribs.utf8", entry);
 		
 		entry = new FPEntry(R.raw.f_ca1b5997, 0, 63588);
 		fpEntries.put("bin/f_skeleton/blinn10_indices.utf8", entry);
 		entry = new FPEntry(R.raw.f_ca1b5997, 63588, 109164);
 		fpEntries.put("bin/f_skeleton/blinn11_indices.utf8", entry);
 		entry = new FPEntry(R.raw.f_ca1b5997, 172752, 145674);
 		fpEntries.put("bin/f_skeleton/blinn12_indices.utf8", entry);
 		entry = new FPEntry(R.raw.f_ca1b5997, 318426, 70848);
 		fpEntries.put("bin/f_skeleton/blinn14_indices.utf8", entry);
 		entry = new FPEntry(R.raw.f_ca1b5997, 389274, 29034);
 		fpEntries.put("bin/f_skeleton/blinn15_indices.utf8", entry);
 		entry = new FPEntry(R.raw.f_ca1b5997, 418308, 73176);
 		fpEntries.put("bin/f_skeleton/blinn16_indices.utf8", entry);
 		entry = new FPEntry(R.raw.f_ca1b5997, 491484, 45276);
 		fpEntries.put("bin/f_skeleton/blinn8_indices.utf8", entry);
 		entry = new FPEntry(R.raw.f_ca1b5997, 536760, 116400);
 		fpEntries.put("bin/f_skeleton/blinn9_indices.utf8", entry);
 		
 		entry = new FPEntry(R.raw.f_3d4225ab, 0, 97824);
 		fpEntries.put("bin/f_skeleton/blinn10_attribs.utf8", entry);
 		entry = new FPEntry(R.raw.f_3d4225ab, 97824, 180048);
 		fpEntries.put("bin/f_skeleton/blinn11_attribs.utf8", entry);
 		entry = new FPEntry(R.raw.f_3d4225ab, 277872, 250248);
 		fpEntries.put("bin/f_skeleton/blinn12_attribs.utf8", entry);
 		entry = new FPEntry(R.raw.f_3d4225ab, 528120, 113632);
 		fpEntries.put("bin/f_skeleton/blinn14_attribs.utf8", entry);
 		entry = new FPEntry(R.raw.f_3d4225ab, 641752, 47840);
 		fpEntries.put("bin/f_skeleton/blinn15_attribs.utf8", entry);
 		entry = new FPEntry(R.raw.f_3d4225ab, 689592, 115952);
 		fpEntries.put("bin/f_skeleton/blinn16_attribs.utf8", entry);
 		entry = new FPEntry(R.raw.f_3d4225ab, 805544, 70416);
 		fpEntries.put("bin/f_skeleton/blinn8_attribs.utf8", entry);
 		entry = new FPEntry(R.raw.f_3d4225ab, 875960, 192912);
 		fpEntries.put("bin/f_skeleton/blinn9_attribs.utf8", entry);
 		
 		entry = new FPEntry(R.raw.f_85ea7cc8, 0, 169302);
 		fpEntries.put("bin/f_connective/lambert2_indices.utf8", entry);
 		entry = new FPEntry(R.raw.f_85ea7cc8, 169302, 23292);
 		fpEntries.put("bin/f_connective/lambert4_indices.utf8", entry);
 		entry = new FPEntry(R.raw.f_85ea7cc8, 192594, 35940);
 		fpEntries.put("bin/f_connective/lambert5_indices.utf8", entry);
 		entry = new FPEntry(R.raw.f_85ea7cc8, 228534, 65370);
 		fpEntries.put("bin/f_connective/lambert6_indices.utf8", entry);
 		entry = new FPEntry(R.raw.f_85ea7cc8, 293904, 15732);
 		fpEntries.put("bin/f_connective/lambert7_indices.utf8", entry);
 		entry = new FPEntry(R.raw.f_85ea7cc8, 309636, 16158);
 		fpEntries.put("bin/f_connective/lambert8_indices.utf8", entry);
 		
 		entry = new FPEntry(R.raw.f_f5246ba2, 0, 277712);
 		fpEntries.put("bin/f_connective/lambert2_attribs.utf8", entry);
 		entry = new FPEntry(R.raw.f_f5246ba2, 277712, 31984);
 		fpEntries.put("bin/f_connective/lambert4_attribs.utf8", entry);
 		entry = new FPEntry(R.raw.f_f5246ba2, 309696, 56608);
 		fpEntries.put("bin/f_connective/lambert5_attribs.utf8", entry);
 		entry = new FPEntry(R.raw.f_f5246ba2, 366304, 107888);
 		fpEntries.put("bin/f_connective/lambert6_attribs.utf8", entry);
 		entry = new FPEntry(R.raw.f_f5246ba2, 474192, 27392);
 		fpEntries.put("bin/f_connective/lambert7_attribs.utf8", entry);
 		entry = new FPEntry(R.raw.f_f5246ba2, 501584, 23120);
 		fpEntries.put("bin/f_connective/lambert8_attribs.utf8", entry);
 		
 		entry = new FPEntry(R.raw.f_79e03caa, 0, 11700);
 		fpEntries.put("bin/f_organs/Female_Repro_SG4_indices.utf8", entry);
 		entry = new FPEntry(R.raw.f_79e03caa, 11700, 1347);
 		fpEntries.put("bin/f_organs/InnerStomach_SG3_indices.utf8", entry);
 		entry = new FPEntry(R.raw.f_79e03caa, 13047, 32508);
 		fpEntries.put("bin/f_organs/Large_Intestine_SG3_indices.utf8", entry);
 		entry = new FPEntry(R.raw.f_79e03caa, 45555, 7101);
 		fpEntries.put("bin/f_organs/Liver_GallB_SG3_indices.utf8", entry);
 		entry = new FPEntry(R.raw.f_79e03caa, 52656, 3249);
 		fpEntries.put("bin/f_organs/Stomach_Spleen_GB_SG3_indices.utf8", entry);
 		entry = new FPEntry(R.raw.f_79e03caa, 55905, 23022);
 		fpEntries.put("bin/f_organs/Upper_Throat_SG3_indices.utf8", entry);
 		entry = new FPEntry(R.raw.f_79e03caa, 78927, 11355);
 		fpEntries.put("bin/f_organs/Urinary_SG4_indices.utf8", entry);
 		entry = new FPEntry(R.raw.f_79e03caa, 90282, 1794);
 		fpEntries.put("bin/f_organs/blinn13_indices.utf8", entry);
 		entry = new FPEntry(R.raw.f_79e03caa, 92076, 50568);
 		fpEntries.put("bin/f_organs/lungs_L_Lung_SG1_indices.utf8", entry);
 		entry = new FPEntry(R.raw.f_79e03caa, 142644, 3570);
 		fpEntries.put("bin/f_organs/lungs_R_Lung_SG1_indices.utf8", entry);
 		entry = new FPEntry(R.raw.f_79e03caa, 146214, 3180);
 		fpEntries.put("bin/f_organs/lungs_pleuraL_SG1_indices.utf8", entry);
 		entry = new FPEntry(R.raw.f_79e03caa, 149394, 3306);
 		fpEntries.put("bin/f_organs/lungs_pleuraR_SG1_indices.utf8", entry);
 		entry = new FPEntry(R.raw.f_79e03caa, 152700, 35772);
 		fpEntries.put("bin/f_organs/nasopharynx_sinus_SG3_indices.utf8", entry);
 		entry = new FPEntry(R.raw.f_79e03caa, 188472, 13356);
 		fpEntries.put("bin/f_organs/small_intestine_SG3_indices.utf8", entry);
 		
 		entry = new FPEntry(R.raw.f_85b3a3ee, 0, 19928);
 		fpEntries.put("bin/f_organs/Female_Repro_SG4_attribs.utf8", entry);
 		entry = new FPEntry(R.raw.f_85b3a3ee, 19928, 2176);
 		fpEntries.put("bin/f_organs/InnerStomach_SG3_attribs.utf8", entry);
 		entry = new FPEntry(R.raw.f_85b3a3ee, 22104, 46400);
 		fpEntries.put("bin/f_organs/Large_Intestine_SG3_attribs.utf8", entry);
 		entry = new FPEntry(R.raw.f_85b3a3ee, 68504, 10488);
 		fpEntries.put("bin/f_organs/Liver_GallB_SG3_attribs.utf8", entry);
 		entry = new FPEntry(R.raw.f_85b3a3ee, 78992, 5336);
 		fpEntries.put("bin/f_organs/Stomach_Spleen_GB_SG3_attribs.utf8", entry);
 		entry = new FPEntry(R.raw.f_85b3a3ee, 84328, 40128);
 		fpEntries.put("bin/f_organs/Upper_Throat_SG3_attribs.utf8", entry);
 		entry = new FPEntry(R.raw.f_85b3a3ee, 124456, 19032);
 		fpEntries.put("bin/f_organs/Urinary_SG4_attribs.utf8", entry);
 		entry = new FPEntry(R.raw.f_85b3a3ee, 143488, 2800);
 		fpEntries.put("bin/f_organs/blinn13_attribs.utf8", entry);
 		entry = new FPEntry(R.raw.f_85b3a3ee, 146288, 69408);
 		fpEntries.put("bin/f_organs/lungs_L_Lung_SG1_attribs.utf8", entry);
 		entry = new FPEntry(R.raw.f_85b3a3ee, 215696, 5672);
 		fpEntries.put("bin/f_organs/lungs_R_Lung_SG1_attribs.utf8", entry);
 		entry = new FPEntry(R.raw.f_85b3a3ee, 221368, 5400);
 		fpEntries.put("bin/f_organs/lungs_pleuraL_SG1_attribs.utf8", entry);
 		entry = new FPEntry(R.raw.f_85b3a3ee, 226768, 5288);
 		fpEntries.put("bin/f_organs/lungs_pleuraR_SG1_attribs.utf8", entry);
 		entry = new FPEntry(R.raw.f_85b3a3ee, 232056, 62016);
 		fpEntries.put("bin/f_organs/nasopharynx_sinus_SG3_attribs.utf8", entry);
 		entry = new FPEntry(R.raw.f_85b3a3ee, 294072, 21240);
 		fpEntries.put("bin/f_organs/small_intestine_SG3_attribs.utf8", entry);
 		
 		entry = new FPEntry(R.raw.f_1338553e, 0, 385731);
 		fpEntries.put("bin/f_circulatory/F_Circulatory_Textured_20th_blinn2_indices.utf8", entry);
 		entry = new FPEntry(R.raw.f_1338553e, 385731, 202068);
 		fpEntries.put("bin/f_circulatory/F_Circulatory_Textured_20th_blinn2_p1_indices.utf8", entry);
 		entry = new FPEntry(R.raw.f_1338553e, 587799, 385002);
 		fpEntries.put("bin/f_circulatory/blinn1_indices.utf8", entry);
 		entry = new FPEntry(R.raw.f_1338553e, 972801, 244077);
 		fpEntries.put("bin/f_circulatory/blinn1_p1_indices.utf8", entry);
 		entry = new FPEntry(R.raw.f_1338553e, 1216878, 29631);
 		fpEntries.put("bin/f_circulatory/blinn3_indices.utf8", entry);
 		entry = new FPEntry(R.raw.f_1338553e, 1246509, 14001);
 		fpEntries.put("bin/f_circulatory/blinn4_indices.utf8", entry);
 		entry = new FPEntry(R.raw.f_1338553e, 1260510, 28047);
 		fpEntries.put("bin/f_circulatory/blinn5_indices.utf8", entry);
 		entry = new FPEntry(R.raw.f_1338553e, 1288557, 16611);
 		fpEntries.put("bin/f_circulatory/blinn6_indices.utf8", entry);
 		
 		entry = new FPEntry(R.raw.f_3629e7b5, 0, 521480);
 		fpEntries.put("bin/f_circulatory/F_Circulatory_Textured_20th_blinn2_attribs.utf8", entry);
 		entry = new FPEntry(R.raw.f_3629e7b5, 521480, 277400);
 		fpEntries.put("bin/f_circulatory/F_Circulatory_Textured_20th_blinn2_p1_attribs.utf8", entry);
 		entry = new FPEntry(R.raw.f_3629e7b5, 798880, 523288);
 		fpEntries.put("bin/f_circulatory/blinn1_attribs.utf8", entry);
 		entry = new FPEntry(R.raw.f_3629e7b5, 1322168, 332016);
 		fpEntries.put("bin/f_circulatory/blinn1_p1_attribs.utf8", entry);
 		entry = new FPEntry(R.raw.f_3629e7b5, 1654184, 45480);
 		fpEntries.put("bin/f_circulatory/blinn3_attribs.utf8", entry);
 		entry = new FPEntry(R.raw.f_3629e7b5, 1699664, 25072);
 		fpEntries.put("bin/f_circulatory/blinn4_attribs.utf8", entry);
 		entry = new FPEntry(R.raw.f_3629e7b5, 1724736, 43088);
 		fpEntries.put("bin/f_circulatory/blinn5_attribs.utf8", entry);
 		entry = new FPEntry(R.raw.f_3629e7b5, 1767824, 27768);
 		fpEntries.put("bin/f_circulatory/blinn6_attribs.utf8", entry);
 		
 		entry = new FPEntry(R.raw.f_b9d30f9a, 0, 30000);
 		fpEntries.put("bin/f_nervous/Dura_Spine3_indices.utf8", entry);
 		entry = new FPEntry(R.raw.f_b9d30f9a, 30000, 375279);
 		fpEntries.put("bin/f_nervous/M_Nervous_Textured_30Percent_blinn1_indices.utf8", entry);
 		entry = new FPEntry(R.raw.f_b9d30f9a, 405279, 375750);
 		fpEntries.put("bin/f_nervous/M_Nervous_Textured_30Percent_blinn1_p1_indices.utf8", entry);
 		entry = new FPEntry(R.raw.f_b9d30f9a, 781029, 271779);
 		fpEntries.put("bin/f_nervous/M_Nervous_Textured_30Percent_blinn1_p2_indices.utf8", entry);
 		entry = new FPEntry(R.raw.f_b9d30f9a, 1052808, 41874);
 		fpEntries.put("bin/f_nervous/M_Nervous_Textured_30Percent_blinn4_indices.utf8", entry);
 		entry = new FPEntry(R.raw.f_b9d30f9a, 1094682, 34467);
 		fpEntries.put("bin/f_nervous/M_Nervous_Textured_30Percent_blinn5_indices.utf8", entry);
 		entry = new FPEntry(R.raw.f_b9d30f9a, 1129149, 28116);
 		fpEntries.put("bin/f_nervous/M_Nervous_Textured_30Percent_blinn6_indices.utf8", entry);
 		entry = new FPEntry(R.raw.f_b9d30f9a, 1157265, 13572);
 		fpEntries.put("bin/f_nervous/blinn7_indices.utf8", entry);
 		entry = new FPEntry(R.raw.f_b9d30f9a, 1170837, 28944);
 		fpEntries.put("bin/f_nervous/phong1_indices.utf8", entry);
 		
 		entry = new FPEntry(R.raw.f_b8150b9a, 0, 43728);
 		fpEntries.put("bin/f_nervous/Dura_Spine3_attribs.utf8", entry);
 		entry = new FPEntry(R.raw.f_b8150b9a, 43728, 524224);
 		fpEntries.put("bin/f_nervous/M_Nervous_Textured_30Percent_blinn1_attribs.utf8", entry);
 		entry = new FPEntry(R.raw.f_b8150b9a, 567952, 503832);
 		fpEntries.put("bin/f_nervous/M_Nervous_Textured_30Percent_blinn1_p1_attribs.utf8", entry);
 		entry = new FPEntry(R.raw.f_b8150b9a, 1071784, 365848);
 		fpEntries.put("bin/f_nervous/M_Nervous_Textured_30Percent_blinn1_p2_attribs.utf8", entry);
 		entry = new FPEntry(R.raw.f_b8150b9a, 1437632, 66328);
 		fpEntries.put("bin/f_nervous/M_Nervous_Textured_30Percent_blinn4_attribs.utf8", entry);
 		entry = new FPEntry(R.raw.f_b8150b9a, 1503960, 52464);
 		fpEntries.put("bin/f_nervous/M_Nervous_Textured_30Percent_blinn5_attribs.utf8", entry);
 		entry = new FPEntry(R.raw.f_b8150b9a, 1556424, 50472);
 		fpEntries.put("bin/f_nervous/M_Nervous_Textured_30Percent_blinn6_attribs.utf8", entry);
 		entry = new FPEntry(R.raw.f_b8150b9a, 1606896, 22816);
 		fpEntries.put("bin/f_nervous/blinn7_attribs.utf8", entry);
 		entry = new FPEntry(R.raw.f_b8150b9a, 1629712, 40896);
 		fpEntries.put("bin/f_nervous/phong1_attribs.utf8", entry);
    }
}
